#!/bin/sh
export Frdict="/home/xfbai/corpus/Bilingual_dict/parallel.fwdxbwd-dict.fr-en"
export Zhdict="/home/xfbai/corpus/Bilingual_dict/google_dict.zh-en"
export Dedict="/home/xfbai/corpus/Bilingual_dict/parallel.fwdxbwd-dict.de-en"
export Fidict="/home/xfbai/corpus/Bilingual_dict/parallel.fwdxbwd-dict.fi-en"
export Hudict="/home/xfbai/corpus/Bilingual_dict/parallel.fwdxbwd-dict.hu-en"
export Frvec="/home/xfbai/tmpvec/new_embedding_size200.fr"
export Zhvec="/home/xfbai/tmpvec/new_embedding_size200.zh"
export Devec="/home/xfbai/tmpvec/new_embedding_size200.de"
export Fivec="/home/xfbai/tmpvec/new_embedding_size200.fi"
export Huvec="/home/xfbai/tmpvec/new_embedding_size200.hu"
export Envec="/home/xfbai/tmpvec/new_embedding_size200.en"
export FrWord="/home/xfbai/tmpvec/fr_wordCount.txt"
export ZhWord="/home/xfbai/tmpvec/zh_wordCount.txt"
export EnWord="/home/xfbai/tmpvec/en_wordCount.txt"
export DeWord="/home/xfbai/tmpvec/de_wordCount.txt"
export FiWord="/home/xfbai/tmpvec/fi_wordCount.txt"
export HuWord="/home/xfbai/tmpvec/hu_wordCount.txt"
set -e
echo "Aligning vectors..."
python alignVectors.py -w1 $Fivec -w2 $Envec -w3 $FiWord -w4 $EnWord -a $Fidict -o Out
